### ISSUE TITLE
👋 Do you know what IM is?

### ISSUE THREAD

**Issue by ChoCho66** [iamarjong/2024Practices#1]
IM is 

invariant measure
invariant measure
invariant measure
invariant measure
invariant measure
invariant measure
invariant measure
invariant measure
invariant measure
invariant measure
invariant measure
invariant measure
invariant measure
invariant measure
invariant measure
invariant measure
invariant measure
invariant measure
invariant measure

**Comment by iamarjong** [comment]
What does this issue belong to ??

**Comment by ChoCho66** [comment]
> What does this issue belong to ??這個問題屬於什麼？

This belongs to the highest level of mathematics, stochastic calculus.

**Comment by ChoCho66** [comment]
> What does this issue belong to ??

Good answer!

**Comment by iamarjong** [comment]
> > What does this issue belong to ??
> 
> Good answer!

Indeed.
